server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/taller
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
spring.jpa.hibernate.show-sql=true

# Dirección base del servicio
taller.server.url=http://45.236.129.192
#taller.server.url=http://localhost